- name: Hello World Sample
  hosts: localhost
  gather_facts: False
  tasks:   
    - name: Say Hello
      debug:
        msg: "Hello World!"
    - name: format the xfs filesystem
      community.general.filesystem:
        fstype: xfs
        dev: /dev/mwapps-vg/mwapps-lv
