- name: Hello World Sample
  hosts: localhost
  gather_facts: False
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:   
    - name: Say Hello
      debug:
        msg: "Hello World!"
